apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-operator-sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: website-operator-sdk
  template:
    metadata:
      labels:
        name: website-operator-sdk
    spec:
      serviceAccountName: website-operator-sdk
      containers:
        - name: website-operator-sdk
          # Replace this with the built image name
          image: architechbootcamp/website-operator:1.0.0
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - website-operator-sdk
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "website-operator-sdk"
