apiVersion: v1
kind: Service
metadata:
  name: kubia-website-lb
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    webserver: kubia-website
  sessionAffinity: None
  type: LoadBalancer
