apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: websites.example.architech.ca
spec:
  group: example.architech.ca
  names:
    kind: Website
    plural: websites
    singular: websites
    shortNames: ['ws']
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            gitRepo:
              type: string
            port:
              format: int32
              type: integer
            replicas:
              format: int32
              type: integer
            targetPort:
              format: int32
              type: integer
          required:
          - gitRepo
          - replicas
          - port
          - targetPort
          type: object
        status:
          properties:
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
