apiVersion: example.architech.ca/v1beta1
kind: Website
metadata:
  name: example-website
spec:
  # Add fields here
  gitRepo: https://github.com/jungho/operator-sdk-site.git
  replicas: 2
  port: 8080
  targetPort: 80
