apiVersion: example.architech.ca/v1beta1
kind: Website
metadata:
  name: example-website
spec:
  # Add fields here
  gitRepo: https://github.com/luksa/kubia-website-example.git
  replicas: 2
  port: 8080
  targetPort: 8080
